<?php
/**
 * AddClientRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AddClientRequestTest Class Doc Comment
 *
 * @category    Class
 * @description AddClientRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddClientRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddClientRequest"
     */
    public function testAddClientRequest()
    {
    }

    /**
     * Test attribute "account_balance"
     */
    public function testPropertyAccountBalance()
    {
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "address_line1"
     */
    public function testPropertyAddressLine1()
    {
    }

    /**
     * Test attribute "address_line2"
     */
    public function testPropertyAddressLine2()
    {
    }

    /**
     * Test attribute "appt_gender_pref_male"
     */
    public function testPropertyApptGenderPrefMale()
    {
    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "client_credit_card"
     */
    public function testPropertyClientCreditCard()
    {
    }

    /**
     * Test attribute "client_indexes"
     */
    public function testPropertyClientIndexes()
    {
    }

    /**
     * Test attribute "client_relationships"
     */
    public function testPropertyClientRelationships()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "custom_client_fields"
     */
    public function testPropertyCustomClientFields()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "emergency_contact_info_email"
     */
    public function testPropertyEmergencyContactInfoEmail()
    {
    }

    /**
     * Test attribute "emergency_contact_info_name"
     */
    public function testPropertyEmergencyContactInfoName()
    {
    }

    /**
     * Test attribute "emergency_contact_info_phone"
     */
    public function testPropertyEmergencyContactInfoPhone()
    {
    }

    /**
     * Test attribute "emergency_contact_info_relationship"
     */
    public function testPropertyEmergencyContactInfoRelationship()
    {
    }

    /**
     * Test attribute "first_appointment_date"
     */
    public function testPropertyFirstAppointmentDate()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "home_location"
     */
    public function testPropertyHomeLocation()
    {
    }

    /**
     * Test attribute "home_phone"
     */
    public function testPropertyHomePhone()
    {
    }

    /**
     * Test attribute "is_company"
     */
    public function testPropertyIsCompany()
    {
    }

    /**
     * Test attribute "is_prospect"
     */
    public function testPropertyIsProspect()
    {
    }

    /**
     * Test attribute "last_formula_notes"
     */
    public function testPropertyLastFormulaNotes()
    {
    }

    /**
     * Test attribute "last_modified_date_time"
     */
    public function testPropertyLastModifiedDateTime()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "liability"
     */
    public function testPropertyLiability()
    {
    }

    /**
     * Test attribute "liability_release"
     */
    public function testPropertyLiabilityRelease()
    {
    }

    /**
     * Test attribute "membership_icon"
     */
    public function testPropertyMembershipIcon()
    {
    }

    /**
     * Test attribute "middle_name"
     */
    public function testPropertyMiddleName()
    {
    }

    /**
     * Test attribute "mobile_phone"
     */
    public function testPropertyMobilePhone()
    {
    }

    /**
     * Test attribute "mobile_provider"
     */
    public function testPropertyMobileProvider()
    {
    }

    /**
     * Test attribute "new_id"
     */
    public function testPropertyNewId()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "photo_url"
     */
    public function testPropertyPhotoUrl()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "prospect_stage"
     */
    public function testPropertyProspectStage()
    {
    }

    /**
     * Test attribute "red_alert"
     */
    public function testPropertyRedAlert()
    {
    }

    /**
     * Test attribute "referred_by"
     */
    public function testPropertyReferredBy()
    {
    }

    /**
     * Test attribute "sales_reps"
     */
    public function testPropertySalesReps()
    {
    }

    /**
     * Test attribute "site_id"
     */
    public function testPropertySiteId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "test"
     */
    public function testPropertyTest()
    {
    }

    /**
     * Test attribute "unique_id"
     */
    public function testPropertyUniqueId()
    {
    }

    /**
     * Test attribute "work_extension"
     */
    public function testPropertyWorkExtension()
    {
    }

    /**
     * Test attribute "work_phone"
     */
    public function testPropertyWorkPhone()
    {
    }

    /**
     * Test attribute "yellow_alert"
     */
    public function testPropertyYellowAlert()
    {
    }

    /**
     * Test attribute "send_schedule_emails"
     */
    public function testPropertySendScheduleEmails()
    {
    }

    /**
     * Test attribute "send_account_emails"
     */
    public function testPropertySendAccountEmails()
    {
    }

    /**
     * Test attribute "send_promotional_emails"
     */
    public function testPropertySendPromotionalEmails()
    {
    }
}
