<?php
/**
 * AddClientToClassRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AddClientToClassRequestTest Class Doc Comment
 *
 * @category    Class
 * @description AddClientToClassRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddClientToClassRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddClientToClassRequest"
     */
    public function testAddClientToClassRequest()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "class_id"
     */
    public function testPropertyClassId()
    {
    }

    /**
     * Test attribute "test"
     */
    public function testPropertyTest()
    {
    }

    /**
     * Test attribute "require_payment"
     */
    public function testPropertyRequirePayment()
    {
    }

    /**
     * Test attribute "waitlist"
     */
    public function testPropertyWaitlist()
    {
    }

    /**
     * Test attribute "send_email"
     */
    public function testPropertySendEmail()
    {
    }

    /**
     * Test attribute "waitlist_entry_id"
     */
    public function testPropertyWaitlistEntryId()
    {
    }

    /**
     * Test attribute "client_service_id"
     */
    public function testPropertyClientServiceId()
    {
    }

    /**
     * Test attribute "cross_regional_booking"
     */
    public function testPropertyCrossRegionalBooking()
    {
    }

    /**
     * Test attribute "cross_regional_booking_client_service_site_id"
     */
    public function testPropertyCrossRegionalBookingClientServiceSiteId()
    {
    }
}
