<?php
/**
 * ContractTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContractTest Class Doc Comment
 *
 * @category    Class
 * @description Contract
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContractTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Contract"
     */
    public function testContract()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "assigns_membership_id"
     */
    public function testPropertyAssignsMembershipId()
    {
    }

    /**
     * Test attribute "assigns_membership_name"
     */
    public function testPropertyAssignsMembershipName()
    {
    }

    /**
     * Test attribute "sold_online"
     */
    public function testPropertySoldOnline()
    {
    }

    /**
     * Test attribute "contract_items"
     */
    public function testPropertyContractItems()
    {
    }

    /**
     * Test attribute "intro_offer"
     */
    public function testPropertyIntroOffer()
    {
    }

    /**
     * Test attribute "autopay_schedule"
     */
    public function testPropertyAutopaySchedule()
    {
    }

    /**
     * Test attribute "number_of_autopays"
     */
    public function testPropertyNumberOfAutopays()
    {
    }

    /**
     * Test attribute "autopay_trigger_type"
     */
    public function testPropertyAutopayTriggerType()
    {
    }

    /**
     * Test attribute "action_upon_completion_of_autopays"
     */
    public function testPropertyActionUponCompletionOfAutopays()
    {
    }

    /**
     * Test attribute "clients_charged_on"
     */
    public function testPropertyClientsChargedOn()
    {
    }

    /**
     * Test attribute "clients_charged_on_specific_date"
     */
    public function testPropertyClientsChargedOnSpecificDate()
    {
    }

    /**
     * Test attribute "discount_amount"
     */
    public function testPropertyDiscountAmount()
    {
    }

    /**
     * Test attribute "deposit_amount"
     */
    public function testPropertyDepositAmount()
    {
    }

    /**
     * Test attribute "first_autopay_free"
     */
    public function testPropertyFirstAutopayFree()
    {
    }

    /**
     * Test attribute "last_autopay_free"
     */
    public function testPropertyLastAutopayFree()
    {
    }

    /**
     * Test attribute "client_terminate_online"
     */
    public function testPropertyClientTerminateOnline()
    {
    }

    /**
     * Test attribute "membership_type_restrictions"
     */
    public function testPropertyMembershipTypeRestrictions()
    {
    }

    /**
     * Test attribute "location_purchase_restriction_ids"
     */
    public function testPropertyLocationPurchaseRestrictionIds()
    {
    }

    /**
     * Test attribute "location_purchase_restriction_names"
     */
    public function testPropertyLocationPurchaseRestrictionNames()
    {
    }

    /**
     * Test attribute "agreement_terms"
     */
    public function testPropertyAgreementTerms()
    {
    }

    /**
     * Test attribute "requires_electronic_confirmation"
     */
    public function testPropertyRequiresElectronicConfirmation()
    {
    }

    /**
     * Test attribute "autopay_enabled"
     */
    public function testPropertyAutopayEnabled()
    {
    }

    /**
     * Test attribute "first_payment_amount_subtotal"
     */
    public function testPropertyFirstPaymentAmountSubtotal()
    {
    }

    /**
     * Test attribute "first_payment_amount_tax"
     */
    public function testPropertyFirstPaymentAmountTax()
    {
    }

    /**
     * Test attribute "first_payment_amount_total"
     */
    public function testPropertyFirstPaymentAmountTotal()
    {
    }

    /**
     * Test attribute "recurring_payment_amount_subtotal"
     */
    public function testPropertyRecurringPaymentAmountSubtotal()
    {
    }

    /**
     * Test attribute "recurring_payment_amount_tax"
     */
    public function testPropertyRecurringPaymentAmountTax()
    {
    }

    /**
     * Test attribute "recurring_payment_amount_total"
     */
    public function testPropertyRecurringPaymentAmountTotal()
    {
    }

    /**
     * Test attribute "total_contract_amount_subtotal"
     */
    public function testPropertyTotalContractAmountSubtotal()
    {
    }

    /**
     * Test attribute "total_contract_amount_tax"
     */
    public function testPropertyTotalContractAmountTax()
    {
    }

    /**
     * Test attribute "total_contract_amount_total"
     */
    public function testPropertyTotalContractAmountTotal()
    {
    }
}
