<?php
/**
 * GiftCardTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GiftCardTest Class Doc Comment
 *
 * @category    Class
 * @description GiftCard
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GiftCardTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GiftCard"
     */
    public function testGiftCard()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "location_ids"
     */
    public function testPropertyLocationIds()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "editable_by_consumer"
     */
    public function testPropertyEditableByConsumer()
    {
    }

    /**
     * Test attribute "card_value"
     */
    public function testPropertyCardValue()
    {
    }

    /**
     * Test attribute "sale_price"
     */
    public function testPropertySalePrice()
    {
    }

    /**
     * Test attribute "sold_online"
     */
    public function testPropertySoldOnline()
    {
    }

    /**
     * Test attribute "membership_restriction_ids"
     */
    public function testPropertyMembershipRestrictionIds()
    {
    }

    /**
     * Test attribute "gift_card_terms"
     */
    public function testPropertyGiftCardTerms()
    {
    }

    /**
     * Test attribute "contact_info"
     */
    public function testPropertyContactInfo()
    {
    }

    /**
     * Test attribute "display_logo"
     */
    public function testPropertyDisplayLogo()
    {
    }

    /**
     * Test attribute "layouts"
     */
    public function testPropertyLayouts()
    {
    }
}
