<?php
/**
 * ModelClassTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ModelClassTest Class Doc Comment
 *
 * @category    Class
 * @description Represents a single class instance. The class meets at the start time, goes until the end time.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelClassTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelClass"
     */
    public function testModelClass()
    {
    }

    /**
     * Test attribute "class_schedule_id"
     */
    public function testPropertyClassScheduleId()
    {
    }

    /**
     * Test attribute "visits"
     */
    public function testPropertyVisits()
    {
    }

    /**
     * Test attribute "clients"
     */
    public function testPropertyClients()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "resource"
     */
    public function testPropertyResource()
    {
    }

    /**
     * Test attribute "max_capacity"
     */
    public function testPropertyMaxCapacity()
    {
    }

    /**
     * Test attribute "web_capacity"
     */
    public function testPropertyWebCapacity()
    {
    }

    /**
     * Test attribute "total_booked"
     */
    public function testPropertyTotalBooked()
    {
    }

    /**
     * Test attribute "total_booked_waitlist"
     */
    public function testPropertyTotalBookedWaitlist()
    {
    }

    /**
     * Test attribute "web_booked"
     */
    public function testPropertyWebBooked()
    {
    }

    /**
     * Test attribute "semester_id"
     */
    public function testPropertySemesterId()
    {
    }

    /**
     * Test attribute "is_canceled"
     */
    public function testPropertyIsCanceled()
    {
    }

    /**
     * Test attribute "substitute"
     */
    public function testPropertySubstitute()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "is_waitlist_available"
     */
    public function testPropertyIsWaitlistAvailable()
    {
    }

    /**
     * Test attribute "is_enrolled"
     */
    public function testPropertyIsEnrolled()
    {
    }

    /**
     * Test attribute "hide_cancel"
     */
    public function testPropertyHideCancel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_available"
     */
    public function testPropertyIsAvailable()
    {
    }

    /**
     * Test attribute "start_date_time"
     */
    public function testPropertyStartDateTime()
    {
    }

    /**
     * Test attribute "end_date_time"
     */
    public function testPropertyEndDateTime()
    {
    }

    /**
     * Test attribute "last_modified_date_time"
     */
    public function testPropertyLastModifiedDateTime()
    {
    }

    /**
     * Test attribute "class_description"
     */
    public function testPropertyClassDescription()
    {
    }

    /**
     * Test attribute "staff"
     */
    public function testPropertyStaff()
    {
    }

    /**
     * Test attribute "booking_window"
     */
    public function testPropertyBookingWindow()
    {
    }

    /**
     * Test attribute "booking_status"
     */
    public function testPropertyBookingStatus()
    {
    }
}
