<?php
/**
 * SubstituteClassTeacherRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SubstituteClassTeacherRequestTest Class Doc Comment
 *
 * @category    Class
 * @description SubstituteClassTeacherRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubstituteClassTeacherRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SubstituteClassTeacherRequest"
     */
    public function testSubstituteClassTeacherRequest()
    {
    }

    /**
     * Test attribute "class_id"
     */
    public function testPropertyClassId()
    {
    }

    /**
     * Test attribute "staff_id"
     */
    public function testPropertyStaffId()
    {
    }

    /**
     * Test attribute "override_conflicts"
     */
    public function testPropertyOverrideConflicts()
    {
    }

    /**
     * Test attribute "send_client_email"
     */
    public function testPropertySendClientEmail()
    {
    }

    /**
     * Test attribute "send_original_teacher_email"
     */
    public function testPropertySendOriginalTeacherEmail()
    {
    }

    /**
     * Test attribute "send_substitute_teacher_email"
     */
    public function testPropertySendSubstituteTeacherEmail()
    {
    }
}
