<?php
/**
 * WaitlistEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MINDBODY Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WaitlistEntryTest Class Doc Comment
 *
 * @category    Class
 * @description WaitlistEntry
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WaitlistEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WaitlistEntry"
     */
    public function testWaitlistEntry()
    {
    }

    /**
     * Test attribute "class_date"
     */
    public function testPropertyClassDate()
    {
    }

    /**
     * Test attribute "class_id"
     */
    public function testPropertyClassId()
    {
    }

    /**
     * Test attribute "class_schedule"
     */
    public function testPropertyClassSchedule()
    {
    }

    /**
     * Test attribute "client"
     */
    public function testPropertyClient()
    {
    }

    /**
     * Test attribute "enrollment_date_forward"
     */
    public function testPropertyEnrollmentDateForward()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "request_date_time"
     */
    public function testPropertyRequestDateTime()
    {
    }

    /**
     * Test attribute "visit_ref_no"
     */
    public function testPropertyVisitRefNo()
    {
    }

    /**
     * Test attribute "web"
     */
    public function testPropertyWeb()
    {
    }
}
